language: scala

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - oraclejdk7
  # Note: not currently testing on JDK 8 internally
  - oraclejdk8
  - openjdk7

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION update

script: ./sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success: ./sbt ++$TRAVIS_SCALA_VERSION coveralls
